// Generated by tools/compile-mwl.mjs from src/content/resistance-rules.mwl.
export const MONSTER_IMMUNITY_DATA = [
  {
    "monster": "dm100",
    "subtype": "",
    "immunities": [
      "bleeding",
      "poison"
    ]
  },
  {
    "monster": "dm200",
    "subtype": "",
    "immunities": [
      "bleeding",
      "poison"
    ]
  },
  {
    "monster": "dm201",
    "subtype": "",
    "immunities": [
      "bleeding",
      "poison"
    ]
  },
  {
    "monster": "dm300",
    "subtype": "",
    "immunities": [
      "bleeding",
      "poison"
    ]
  },
  {
    "monster": "golem",
    "subtype": "",
    "immunities": [
      "bleeding",
      "poison"
    ]
  },
  {
    "monster": "skeleton",
    "subtype": "",
    "immunities": [
      "bleeding",
      "poison"
    ]
  },
  {
    "monster": "necroSkeleton",
    "subtype": "",
    "immunities": [
      "bleeding",
      "poison"
    ]
  },
  {
    "monster": "statue",
    "subtype": "",
    "immunities": [
      "bleeding",
      "poison"
    ]
  },
  {
    "monster": "armoredStatue",
    "subtype": "",
    "immunities": [
      "bleeding",
      "poison"
    ]
  },
  {
    "monster": "pylon",
    "subtype": "",
    "immunities": [
      "bleeding",
      "poison",
      "terror",
      "amok",
      "charm",
      "paralysis",
      "frost",
      "chill"
    ]
  },
  {
    "monster": "demonSpawner",
    "subtype": "",
    "immunities": [
      "terror",
      "amok",
      "charm",
      "paralysis",
      "frost",
      "chill"
    ]
  },
  {
    "monster": "rotHeart",
    "subtype": "",
    "immunities": [
      "terror",
      "amok",
      "charm",
      "paralysis",
      "frost",
      "chill"
    ]
  },
  {
    "monster": "yog",
    "subtype": "",
    "immunities": [
      "terror",
      "amok",
      "charm",
      "paralysis",
      "frost",
      "chill"
    ]
  },
  {
    "monster": "ninjaLog",
    "subtype": "",
    "immunities": [
      "terror",
      "amok",
      "charm",
      "bleeding",
      "poison"
    ]
  },
  {
    "monster": "goo",
    "subtype": "",
    "immunities": [
      "ooze"
    ]
  },
  {
    "monster": "acidic",
    "subtype": "",
    "immunities": [
      "ooze"
    ]
  },
  {
    "monster": "causticSlime",
    "subtype": "",
    "immunities": [
      "ooze"
    ]
  },
  {
    "monster": "yogFist",
    "subtype": "rotting",
    "immunities": [
      "ooze"
    ]
  },
  {
    "monster": "yogFist",
    "subtype": "burning",
    "immunities": [
      "burning"
    ]
  },
  {
    "monster": "yogFist",
    "subtype": "rusted",
    "immunities": [
      "bleeding",
      "poison"
    ]
  },
  {
    "monster": "succubus",
    "subtype": "",
    "immunities": [
      "charm"
    ]
  },
  {
    "monster": "tengu",
    "subtype": "",
    "immunities": [
      "roots",
      "terror",
      "blindness"
    ]
  },
  {
    "monster": "piranha",
    "subtype": "",
    "immunities": [
      "burning"
    ]
  }
] as const;
