// Generated by tools/compile-mwl.mjs from src/content/actor-rules.mwl.
export const GOO_STATE_STATS = {
  "healthy": {
    "accuracy": 10,
    "evasion": 8,
    "damageMin": 1,
    "damageMax": 8
  },
  "enraged": {
    "accuracy": 15,
    "evasion": 12,
    "damageMin": 1,
    "damageMax": 12
  }
} as const;
export const BRUTE_RAGE_DAMAGE = {
  "brute": [
    15,
    40
  ],
  "armoredBrute": [
    15,
    40
  ]
} as const;
