// Generated by tools/compile-mwl.mjs from src/content/resistance-rules.mwl.
export const STATUS_IMMUNITIES = {
  "fire": [
    "burning"
  ],
  "magic": [
    "charm",
    "weakness",
    "vulnerable",
    "hex",
    "degrade",
    "magicalSleep"
  ],
  "chill": [
    "chill"
  ]
} as const;
