import { readdir, readFile, mkdir, writeFile, stat, rm } from 'node:fs/promises';
import { join, extname, relative, dirname, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ASSET_GROUPS, MESSAGE_LOCALES, MIME } from './manifest.mjs';
import { parseProperties, localeOf } from './compile-messages.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..', '..');

//assets still live with the java modules: everything but the fallback asian font is in
//core, and droid_sans sits with the desktop build
const CORE_ASSETS = join(repo, 'core', 'src', 'main', 'assets');
const DESKTOP_ASSETS = join(repo, 'desktop', 'src', 'main', 'assets');

const OUT = join(here, '..', 'dist', 'assets');

async function* walk(dir) {
	let entries;
	try {
		entries = await readdir(dir, { withFileTypes: true });
	} catch {
		return;
	}
	for (const entry of entries) {
		const full = join(dir, entry.name);
		if (entry.isDirectory()) yield* walk(full);
		else yield full;
	}
}

const keyOf = (file) => relative(CORE_ASSETS, file).split(sep).join('/');

function shouldIncludeMessage(key) {
	//messages are named like actors.properties / actors_fr.properties
	const base = key.replace(/\.properties$/, '');
	return MESSAGE_LOCALES.some((locale) =>
		locale === '' ? !/_[a-z]{2}(_[A-Z]{2})?$/.test(base) : base.endsWith(locale)
	);
}

async function encode(file, mime) {
	const data = await readFile(file);
	return { uri: `data:${mime};base64,${data.toString('base64')}`, bytes: data.length };
}

/** one group becomes one script that merges its entries into the shared asset map */
async function writeGroup(name, assets) {
	const body = JSON.stringify(assets);
	const js =
		`//generated by tools/collect-assets.mjs, do not edit\n` +
		`(function(){var a=window.__SPD_ASSETS__||(window.__SPD_ASSETS__={});` +
		`var g=${body};for(var k in g)a[k]=g[k];})();\n`;
	await writeFile(join(OUT, `${name}.js`), js, 'utf8');
	return js.length;
}

await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });

const written = [];
let totalRaw = 0;
let totalOut = 0;

for (const [group, dirs] of Object.entries(ASSET_GROUPS)) {
	const assets = {};
	let raw = 0;

	for (const dir of dirs) {
		for await (const file of walk(join(CORE_ASSETS, dir))) {
			const mime = MIME[extname(file).toLowerCase()];
			if (!mime) continue;
			const { uri, bytes } = await encode(file, mime);
			assets[keyOf(file)] = uri;
			raw += bytes;
		}
	}

	//the fallback font for asian glyphs lives with the desktop build
	if (group === 'fonts') {
		const font = join(DESKTOP_ASSETS, 'fonts', 'droid_sans.ttf');
		try {
			await stat(font);
			const { uri, bytes } = await encode(font, MIME['.ttf']);
			assets['fonts/droid_sans.ttf'] = uri;
			raw += bytes;
		} catch {
			console.warn('droid_sans.ttf not found, asian glyphs will use the pixel font');
		}
	}

	if (Object.keys(assets).length === 0) continue;

	const size = await writeGroup(group, assets);
	written.push({ group, count: Object.keys(assets).length, size });
	totalRaw += raw;
	totalOut += size;
}

//messages are compiled rather than carried as files: the .properties are parsed here so
//that Messages.get() in the game is a plain synchronous lookup, as it is on the other
//platforms, instead of decoding text on startup
{
	const byLocale = {};
	let raw = 0;
	let files = 0;

	for await (const file of walk(join(CORE_ASSETS, 'messages'))) {
		const key = keyOf(file);
		if (extname(file) !== '.properties' || !shouldIncludeMessage(key)) continue;

		const text = await readFile(file, 'utf8');
		const locale = localeOf(key);
		const entries = parseProperties(text);

		byLocale[locale] = Object.assign(byLocale[locale] ?? {}, entries);
		raw += Buffer.byteLength(text);
		files++;
	}

	const locales = Object.keys(byLocale);
	if (locales.length > 0) {
		const js =
			`//generated by tools/collect-assets.mjs, do not edit\n` +
			`window.__SPD_MESSAGES__=${JSON.stringify(byLocale)};\n`;
		await writeFile(join(OUT, 'messages.js'), js, 'utf8');

		const keys = locales.reduce((n, l) => n + Object.keys(byLocale[l]).length, 0);
		written.push({ group: 'messages', count: keys, size: js.length });
		totalRaw += raw;
		totalOut += js.length;
		console.log(`  compiled ${files} .properties into ${locales.length} locales (${locales.join(', ')})`);
	}
}

const kb = (n) => (n / 1024).toFixed(0).padStart(6) + ' KB';
for (const { group, count, size } of written) {
	console.log(`  assets/${group}.js`.padEnd(28) + kb(size) + `  (${count} files)`);
}
console.log(`  ${written.length} asset files, ${kb(totalRaw)} raw -> ${kb(totalOut)} written`);

//the page lists these scripts statically: a file:// page cannot read a directory
export const GROUPS = written.map((w) => w.group);
