const fs=require('fs');
function rep(p,a,b){let s=fs.readFileSync(p,'utf8');if(s.includes('\r\n')){a=a.replace(/\n/g,'\r\n');b=b.replace(/\n/g,'\r\n');}const i=s.indexOf(a);if(i<0||s.indexOf(a,i+1)>=0)throw new Error(p+': '+a);s=s.slice(0,i)+b+s.slice(i+a.length);fs.writeFileSync(p,s);}
// A. status pane state
rep('src/scenes/dungeon/deathSaveRefresh.ts',"			armorTier: this.armorTier,\n			interfaceSize: this.interfaceSize,\n			busy:","			armorTier: this.armorTier,\n			interfaceSize: effectiveInterfaceSize(this.interfaceSize, Game.current.width, Game.current.height),\n			busy:");
rep('src/scenes/dungeon/deathSaveRefresh.ts',"import { Actors, AnimatedSprite,","import { effectiveInterfaceSize } from '../../ui/interfaceMode';\nimport { Actors, AnimatedSprite,");
// G. window detail-only
const w='src/ui/inventoryWindow.ts';
rep(w,"	private wide = false;\n","	private wide = false;\n	/** Opened from the docked pane: only the item's detail card shows, and dismissing it closes. */\n	private detailOnly = false;\n");
rep(w,"	private dismissDetail(): void {\n		this.chosen = null; this.detail.visible = false; this.panel.alpha = 1; this.panel.eventMode = 'static'; this.draw();\n	}\n\n	reset(): void { this.chosen = null; this.detail.visible = false; this.panel.alpha = 1; this.panel.eventMode = 'static'; }",
"	/** A docked-pane slot tap: the same detail card the bag grid opens, without the bag behind it. */\n	inspect(item: InventoryEntry): void {\n		this.showItem(item);\n		this.detailOnly = true;\n		this.panel.visible = false;\n	}\n\n	private dismissDetail(): void {\n		const closing = this.detailOnly;\n		this.chosen = null; this.detail.visible = false; this.panel.alpha = 1; this.panel.eventMode = 'static';\n		this.detailOnly = false; this.panel.visible = true;\n		if (closing) this.close(); else this.draw();\n	}\n\n	reset(): void { this.chosen = null; this.detail.visible = false; this.panel.alpha = 1; this.panel.eventMode = 'static'; this.detailOnly = false; this.panel.visible = true; }");
// B. inventoryPanel view
const p='src/ui/inventoryPanel.ts';
rep(p,"import { InventoryWindow, type InventoryEntry } from './inventoryWindow';","import { InventoryWindow, type InventoryEntry } from './inventoryWindow';\nimport type { InventoryDock } from './inventoryDock';");
rep(p,"	readonly weaponName: string;","	readonly weaponName: string;\n	/** The docked pane (`InventoryPane`), when the large interface shows it, and the strength readouts its slots print. */\n	readonly dock: InventoryDock | null;\n	readonly weaponLevel: number;\n	readonly weaponStrReq: number;\n	readonly armorStrReq: number;\n	readonly heroStr: number;");
rep(p,"	panel.visible = context.open;\n	if (!context.open) return;","	panel.visible = context.open;\n	if (!context.open && !context.dock) return;");
rep(p,"		frame: context.weaponFrame, quantity: 1, identified: true, description: context.weaponDescription };","		frame: context.weaponFrame, quantity: 1, identified: true, description: context.weaponDescription, level: context.weaponLevel };\n	//`ItemSlot.updateText()`: `:%d` strength requirement, red when the hero is too weak for it.\n	const strain = (req: number) => ({ extra: `:${req}`, extraColor: req > context.heroStr ? 0xff4444 : 0xffffff });\n	Object.assign(weapon, strain(context.weaponStrReq));\n	if (armor) Object.assign(armor, strain(context.armorStrReq));");
rep(p,"	panel.setWide(context.wide);\n	panel.setItems([weapon, armor, artifact, null, ring], rows.filter(item => item !== artifact && item.id !== context.armorId), context.gold);\n	context.addToStage(panel);","	const carried = rows.filter(item => item !== artifact && item.id !== context.armorId);\n	if (context.dock) context.dock.setItems([weapon, armor, artifact, null, ring], carried, context.gold);\n	if (context.open) {\n		panel.setWide(context.wide);\n		panel.setItems([weapon, armor, artifact, null, ring], carried, context.gold);\n	}\n	context.addToStage(panel);");
