const fs=require('fs');
function rep(p,a,b){let s=fs.readFileSync(p,'utf8');if(s.includes('\r\n')){a=a.replace(/\n/g,'\r\n');b=b.replace(/\n/g,'\r\n');}const i=s.indexOf(a);if(i<0||s.indexOf(a,i+1)>=0)throw new Error(p+': '+a);s=s.slice(0,i)+b+s.slice(i+a.length);fs.writeFileSync(p,s);}
const T='{ left: number; wait: number } | null';
rep('src/scenes/dungeonScene.ts',"(CursedWand VeryRare, v4.0.0)\n","(CursedWand VeryRare, v4.0.0)\n".replace("\n","")+"\tgravityChaos: "+T+" = null; //`GravityChaosTracker`\n");
rep('src/scenes/dungeon/deathSaveRefresh.ts',"			superNova: this.superNova,\n","			superNova: this.superNova,\n			gravityChaos: this.gravityChaos,\n");
rep('src/scenes/dungeon/panelsSingleUse.ts',"		this.superNova = s.superNova ?? null;\n","		this.superNova = s.superNova ?? null;\n		this.gravityChaos = s.gravityChaos ?? null;\n");
rep('src/scenes/dungeon/shared.ts',"	superNova?:","	gravityChaos?: "+T+";\n	superNova?:");
rep('src/scenes/dungeon/turnLoopAiming.ts',"		this.tickSuperNova();\n","		this.tickSuperNova();\n		this.tickGravityChaos();\n");
const c='src/scenes/dungeon/hero/cursedWandCast.ts';
rep(c,"		} else if (effect === 'abortRetryFail') {","		} else if (effect === 'gravityChaos') {\n			//`GravityChaos.effect()`: `Buff.append(GravityChaosTracker)` on the caster (`positiveOnly`\n			//unreachable, so allies are pushed too). Lasts `NormalIntRange(30, 70)` pushes.\n			this.gravityChaos = { left: Math.round(Random.normalRange(30, 70)), wait: 0 };\n			runState.audio.cue('teleport', 0.7);\n			this.say(t('items.wands.cursedwand.gravity'), 'warning');\n		} else if (effect === 'abortRetryFail') {");
rep(c,"	/** `new Bomb.ConjuredBomb().explode(cell)`, shared","	/** `GravityChaosTracker.act()` (`v4.0.0`), once per hero action: on each of its `left` turns (spaced\n	 * `IntRange(1, 3)` apart) every non-IMMOVABLE character, the hero included, is thrown 3 cells in one\n	 * shared random `NEIGHBOURS8` direction, and sleeping mobs wake. **Simplified:** a push stops at a wall or\n	 * occupant and before a chasm cell (Java's `throwChar` lets a non-flyer fall), and a character blocked by\n	 * another is not re-pushed the same turn once the blocker moves (Java's `blocked` retry loop). */\n	tickGravityChaos(this: DungeonScene): void {\n		const gravity = this.gravityChaos;\n		if (!gravity) return;\n		if (gravity.wait > 0) { gravity.wait--; return; }\n		const [dx, dy] = Random.element(Roguelike.neighbourOffsets(8) as ReadonlyArray<readonly [number, number]>)!;\n		for (const ch of [...this.creatures]) {\n			if (ch.hp <= 0 || (ch.kind !== undefined && IMMOVABLE_KINDS.has(ch.kind))) continue;\n			if (ch.sleeping) ch.sleeping = false;\n			let last: Step | undefined;\n			for (let step = 1, x = ch.x, y = ch.y; step <= 3; step++) {\n				x += dx; y += dy;\n				if (!this.level.inside(x, y) || !this.level.passable(x, y) || this.creatureAt(x, y) !== null) break;\n				if (this.isChasmCell(x, y) && !ch.flying) break;\n				last = { x, y };\n			}\n			if (last) this.moveTo(ch, last);\n		}\n		if (--gravity.left <= 0) {\n			this.gravityChaos = null;\n			runState.audio.cue('degrade', 0.7);\n			this.say(t('items.wands.cursedwand.gravity_end'), 'warning');\n		} else gravity.wait = Random.int(3);\n	},\n\n	/** `new Bomb.ConjuredBomb().explode(cell)`, shared");
