const fs=require('fs');
function rep(p,a,b){let s=fs.readFileSync(p,'utf8');if(s.includes('\r\n')){a=a.replace(/\n/g,'\r\n');b=b.replace(/\n/g,'\r\n');}const i=s.indexOf(a);if(i<0||s.indexOf(a,i+1)>=0)throw new Error(p+': '+a);s=s.slice(0,i)+b+s.slice(i+a.length);fs.writeFileSync(p,s);}
const f='src/scenes/dungeon/coreSpawnTiles.ts';
rep(f,"		const curtain = new Graphics().rect(0, 0, Game.current.width, Game.current.height).fill(new FillGradient({","		const gradient = new Graphics().rect(0, 0, Game.current.width, Game.current.height).fill(new FillGradient({");
rep(f,"		const message = new Label({ text: t('scenes.interlevelscene$mode.descend')","		//Java's `aa` term (extra opacity in the first/last 0.333s of the fades) is a black veil over the gradient.\n		const curtain = new Graphics().rect(0, 0, Game.current.width, Game.current.height).fill(0x000000);\n		const message = new Label({ text: t('scenes.interlevelscene$mode.descend')");
rep(f,"		root.addChild(backdrop, curtain, message);","		root.addChild(backdrop, gradient, curtain, message);");
rep(f,"		//Java's SLOW_FADE applies to a fresh run and to the first floor of a new region;\n		//the 0.33s in/out fades are added either side of its central dwell time.\n		const slow = this.depth === 1 || this.depth % 5 === 1;\n		this.interlevel = { root, backdrop, elapsed: 0, duration: slow ? 1.66 : 1.33, curtain, message };","		//Java's `fadeTime` (`InterlevelScene.create`): SLOW_FADE 1.0 for a fresh run and the first visit to\n		//floors 6/11/16/21, FAST_FADE 0.5 for a floor already reached, else NORM_FADE 0.67; the scene shows\n		//FADE_IN then FADE_OUT of `fadeTime` each. Generation here is instant, so there is no STATIC wait, and\n		//`deepestDepth` may already count this floor on a first visit (stated approximation).\n		const fadeTime = this.deepestDepth > this.depth ? 0.5 : (this.depth === 1 || this.depth % 5 === 1) ? 1 : 0.67;\n		this.interlevel = { root, backdrop, elapsed: 0, duration: 2 * fadeTime, curtain, message };");
const d='src/scenes/dungeonScene.ts';
rep(d,"			const fade = 0.33;\n			transition.curtain.alpha = transition.elapsed < fade ? 1 - transition.elapsed / fade\n				: transition.elapsed > transition.duration - fade ? (transition.elapsed - (transition.duration - fade)) / fade : 0;\n			transition.message.alpha = 1 - transition.curtain.alpha;","			const half = transition.duration / 2;\n			const left = transition.duration - transition.elapsed;\n			//`InterlevelScene`'s gradient stays up throughout; `aa` adds up to 0.333 opacity at either end, and\n			//the mode text fades in over the first `fadeTime` and out over the second.\n			transition.curtain.alpha = transition.elapsed < half ? Math.max(0, 0.333 - transition.elapsed) : Math.max(0, 0.333 - left);\n			transition.message.alpha = transition.elapsed < half ? transition.elapsed / half : left / half;");
