const fs=require('fs');
function rep(p,a,b){let s=fs.readFileSync(p,'utf8');if(s.includes('\r\n')){a=a.replace(/\n/g,'\r\n');b=b.replace(/\n/g,'\r\n');}const i=s.indexOf(a);if(i<0||s.indexOf(a,i+1)>=0)throw new Error(p+': '+a);s=s.slice(0,i)+b+s.slice(i+a.length);fs.writeFileSync(p,s);}
rep('src/scenes/dungeonScene.ts',"	timeBubbleTurns = 0;\n","	timeBubbleTurns = 0;\n	/** `SuperNovaTracker` (CursedWand VeryRare, `v4.0.0`): the pending blast, kept on the hero in Java so it survives floor changes. */\n	superNova: { x: number; y: number; depth: number; turnsLeft: number } | null = null;\n");
rep('src/scenes/dungeon/deathSaveRefresh.ts',"			timeBubbleTurns: this.timeBubbleTurns,\n","			timeBubbleTurns: this.timeBubbleTurns,\n			superNova: this.superNova,\n");
rep('src/scenes/dungeon/panelsSingleUse.ts',"		this.timeBubbleTurns = s.timeBubbleTurns ?? 0;\n","		this.timeBubbleTurns = s.timeBubbleTurns ?? 0;\n		this.superNova = s.superNova ?? null;\n");
rep('src/scenes/dungeon/shared.ts',"	timeBubbleTurns?: number;\n","	timeBubbleTurns?: number;\n	superNova?: { x: number; y: number; depth: number; turnsLeft: number } | null;\n");
rep('src/scenes/dungeon/turnLoopAiming.ts',"		if (this.enhancedRingsTurns > 0) {","		this.tickSuperNova();\n		if (this.enhancedRingsTurns > 0) {");
const c='src/scenes/dungeon/hero/cursedWandCast.ts';
rep(c,"		} else if (effect === 'abortRetryFail') {","		} else if (effect === 'superNova') {\n			//`SuperNova.effect()`: `Buff.append(SuperNovaTracker)` at the bolt's collision cell. Java's\n			//`positiveOnly`/`harmsAllies=false` branch is unreachable from WildMagic (ROADMAP R061,\n			//WondrousResin), so the blast always harms everyone.\n			this.superNova = { x: cell.x, y: cell.y, depth: this.depth, turnsLeft: 10 };\n			this.say(t('items.wands.cursedwand.supernova'), 'warning');\n		} else if (effect === 'abortRetryFail') {");
rep(c,"castCursedWandVeryRareEffect(this: DungeonScene): void {","castCursedWandVeryRareEffect(this: DungeonScene, cell: Step): void {");
rep(c,"else this.castCursedWandVeryRareEffect();","else this.castCursedWandVeryRareEffect(cell);");
rep(c,"	/** `new Bomb.ConjuredBomb().explode(cell)`","	/** `SuperNovaTracker.act()` (`v4.0.0`), once per hero action: ten countdown ticks, then a\n	 * `ConjuredBomb` at every non-solid cell of a radius-8 field of view from the target cell (a\n	 * cell inside takes up to nine bombs). Java ticks per actor time unit and waits while the hero is\n	 * on another floor; this ticks per hero action on the same floor only. Deliberate reductions:\n	 * the growing halo/floating countdown and `Level.destroy(cell)` (door/barricade removal) are not\n	 * presented, and FOV reads terrain transparency in place of Java's `solid`. */\n	tickSuperNova(this: DungeonScene): void {\n		const nova = this.superNova;\n		if (!nova || nova.depth !== this.depth) return;\n		if (nova.turnsLeft-- > 0) return;\n		this.superNova = null;\n		const fov = new Roguelike.FieldOfView(this.level);\n		fov.update(nova.x, nova.y, 8);\n		const cells: { x: number; y: number }[] = [];\n		for (let y = 0; y < this.level.height; y++) for (let x = 0; x < this.level.width; x++) {\n			if (fov.isVisible(x, y) && this.level.transparent(x, y)) cells.push({ x, y });\n		}\n		runState.audio.cue('blast', 0.7);\n		this.shakeScreen(5, 2);\n		for (const cell of cells) this.explodeConjuredBomb(cell);\n	},\n\n	/** `new Bomb.ConjuredBomb().explode(cell)`");
