const fs=require('fs');
function rep(p,a,b){let s=fs.readFileSync(p,'utf8');if(s.includes('\r\n')){a=a.replace(/\n/g,'\r\n');b=b.replace(/\n/g,'\r\n');}const i=s.indexOf(a);if(i<0||s.indexOf(a,i+1)>=0)throw new Error(p+': '+a);s=s.slice(0,i)+b+s.slice(i+a.length);fs.writeFileSync(p,s);}
const f='src/ui/statusPane.ts';
// header doc
rep(f," *  - `large` variant (`SPDSettings.interfaceSize() == 1`): the pane doubles its bar widths\n *    and buff icon stride; this port renders the same content at 1.5x scale with a taller\n *    buff row rather than Java's exact large pixel cuts (stated simplification). The buff\n *    icons themselves do switch to Java's real separate `BUFFS_LARGE` 16x16 sheet though\n *    (`BuffIcon`'s `large ? BUFFS_LARGE : BUFFS_SMALL`), not just a stretched copy of the\n *    small one.\n",
" *  - `large` variant (`SPDSettings.interfaceSize() > 0`, Java's exact cuts, ported 2026-09-28):\n *    frame `NinePatch(asset, 0, 64, 41, 39, 33, 0, 4, 0)` sized 160x39; HP strip\n *    `Image(asset, 0, 103, 128, 9)` at (30,19), shielded/raw `(0, 112, 128, 9)`; EXP strip\n *    `Image(asset, 0, 121, 128, 7)` at (30,30); centred `hp/max` and `exp/max` readouts on the strips\n *    at 0.6 alpha; the level as `lv. N` under the portrait; buffs at (31,0) on the real\n *    `BUFFS_LARGE` 16x16 sheet. No place label (Java has none; the depth lives in the menu pane).\n");
// constructor: stash sheet + build large group
rep(f,"	private large = false;\n","	private large = false;\n	private readonly statusSheet: Texture;\n	private smallParts: Container[] = [];\n	private largeGroup = new Container();\n	private largeFrame!: NinePatch;\n	private largeHp!: Sprite;\n	private largeShielded!: Sprite;\n	private largeRaw!: Sprite;\n	private largeExp!: Sprite;\n	private largeHpText!: Label;\n	private largeExpText!: Label;\n	private largeLevel!: Label;\n");
rep(f,"		this.buffIconsSmall = buffs;\n","		this.statusSheet = statusSheet;\n		this.buffIconsSmall = buffs;\n");
rep(f,"		this.buffLayer.x = 30 * SCALE;\n		this.buffLayer.y = 9 * SCALE;\n		this.addChild(this.buffLayer);\n	}\n",
"		this.buffLayer.x = 30 * SCALE;\n		this.buffLayer.y = 9 * SCALE;\n		this.addChild(this.buffLayer);\n		this.smallParts = [frame, this.hpFill, this.expFill, this.hpText, this.levelText, this.placeText, this.busyPip];\n		this.buildLarge();\n	}\n\n	private strip(y: number, h: number): Sprite {\n		return new Sprite(new Texture({ source: this.statusSheet.source, frame: new Rectangle(0, y, PANE_WIDTH, h) }));\n	}\n\n	/** `StatusPane`'s `large` constructor/layout branch, kept in its own group and swapped in by `update`. */\n	private buildLarge(): void {\n		const frameTexture = new Texture({ source: this.statusSheet.source, frame: new Rectangle(0, 64, 41, 39) });\n		this.largeFrame = new NinePatch(frameTexture, { border: { left: 33, top: 0, right: 4, bottom: 0 } });\n		this.largeFrame.resize(160, 39);\n		this.largeFrame.scale.set(SCALE);\n		this.largeRaw = this.strip(112, 9);\n		this.largeRaw.alpha = 0.5;\n		this.largeShielded = this.strip(112, 9);\n		this.largeHp = this.strip(103, 9);\n		this.largeExp = this.strip(121, 7);\n		for (const [sprite, y] of [[this.largeRaw, 19], [this.largeShielded, 19], [this.largeHp, 19], [this.largeExp, 30]] as const) {\n			sprite.position.set(30 * SCALE, y * SCALE);\n			sprite.scale.set(SCALE);\n		}\n		//pixel-font BitmapText at scale 1 is this port's size-12 Label (the level tag's size)\n		this.largeHpText = new Label({ size: 12, color: 0xffffff });\n		this.largeHpText.alpha = 0.6;\n		this.largeExpText = new Label({ size: 12, color: 0xffffaa });\n		this.largeExpText.alpha = 0.6;\n		this.largeLevel = new Label({ size: 12, color: 0xffffaa });\n		this.largeLevel.anchor.set(0.5, 0.5);\n		this.largeLevel.position.set(15 * SCALE, 35 * SCALE);\n		this.largeGroup.addChild(this.largeFrame, this.largeRaw, this.largeShielded, this.largeHp, this.largeExp, this.largeHpText, this.largeExpText, this.largeLevel);\n		this.largeGroup.visible = false;\n		//behind the avatar, like the small frame\n		this.addChildAt(this.largeGroup, 0);\n	}\n\n	/** Rendered height of the current layout (`StatusPane.layout()`: 39 large, 32 small; the small frame is 36 tall). */\n	get paneHeight(): number { return (this.large ? 39 : 36) * SCALE; }\n");
// update: replace large switch
rep(f,"		//`SPDSettings.interfaceSize()`: large renders the same pane at 1.5x with a taller buff\n		//row rather than Java's exact large pixel cuts (stated simplification above).\n		const wantLarge = (state.interfaceSize ?? 0) === 1;\n		if (wantLarge !== this.large) {\n			this.large = wantLarge;\n			this.scale.set(wantLarge ? 1.5 : 1);\n","		//`SPDSettings.interfaceSize() > 0`: Java's exact large cuts (see the header).\n		const wantLarge = (state.interfaceSize ?? 0) === 1;\n		if (wantLarge !== this.large) {\n			this.large = wantLarge;\n			this.largeGroup.visible = wantLarge;\n			for (const part of this.smallParts) part.visible = !wantLarge;\n			this.avatar.position.set(9 * SCALE, (wantLarge ? 7.5 : 8) * SCALE);\n			this.buffLayer.position.set((wantLarge ? 31 : 30) * SCALE, (wantLarge ? 0 : 9) * SCALE);\n			this.hitArea = new Rectangle(0, 0, (wantLarge ? 160 : PANE_WIDTH) * SCALE, (wantLarge ? 39 : 36) * SCALE);\n");
rep(f,"		this.busyPip.visible = state.busy === true;\n","		this.busyPip.visible = !this.large && state.busy === true;\n");
rep(f,"		this.levelText.setText(String(state.level));\n","		this.levelText.setText(String(state.level));\n		if (this.large) {\n			const max = Math.max(1, state.maxHp);\n			this.largeHp.scale.x = SCALE * Math.max(0, state.hp - shield) / max;\n			this.largeShielded.scale.x = SCALE * Math.max(0, state.hp) / max;\n			this.largeRaw.scale.x = shield > state.hp ? SCALE * Math.min(1, shield / max) : 0;\n			this.largeExp.scale.x = SCALE * expFraction;\n			this.largeHpText.setText(shield <= 0 ? `${Math.max(0, state.hp)}/${state.maxHp}` : `${Math.max(0, state.hp)}+${shield}/${state.maxHp}`);\n			this.largeHpText.position.set((30 + (128 - this.largeHpText.width / SCALE) / 2) * SCALE, 20 * SCALE);\n			this.largeExpText.setText(`${state.exp}/${state.maxExp}`);\n			this.largeExpText.position.set((30 + (128 - this.largeExpText.width / SCALE) / 2) * SCALE, 30 * SCALE);\n			this.largeLevel.setText(`lv. ${state.level}`);\n		}\n");
rep(f,"		this.talentDot.visible = state.talentPointsAvailable === true;\n","		this.talentDot.visible = state.talentPointsAvailable === true;\n		if (this.large) this.talentDot.position.set(20 * SCALE, 9 * SCALE);\n");
