"""Extract atlas indices from local Java trap/plant classes. No network required."""
from pathlib import Path
import json
import re

root = Path(__file__).resolve().parents[2]
source = root / 'core/src/main/java/com/shatteredpixel/shatteredpixeldungeon'
trap_dir = source / 'levels/traps'
base = (trap_dir / 'Trap.java').read_text()
constants = {k: int(v) for k, v in re.findall(r'public static final int\s+(\w+)\s*=\s*(\d+)', base)}
def values(name):
    if name == 'Trap':
        return {'color': 0, 'shape': 0}
    text = (trap_dir / f'{name}.java').read_text()
    parent = re.search(r'class\s+' + name + r'\s+extends\s+(\w+)', text)
    result = values(parent[1])
    for key, value in re.findall(r'\b(color|shape)\s*=\s*(\w+)\s*;', text):
        result[key] = int(value) if value.isdigit() else constants[value]
    return result
traps = {}
for path in sorted(trap_dir.glob('*.java')):
    if path.stem == 'Trap':
        continue
    value = values(path.stem)
    traps[path.stem] = value['color'] + 16 * value['shape']
plants = {}
for path in sorted((source / 'plants').glob('*.java')):
    match = re.search(r'\bimage\s*=\s*(\d+)\s*;', path.read_text())
    if match:
        plants[path.stem] = 112 + int(match[1])
output = root / 'web-mwg/src/generated/terrainVisuals.ts'
output.write_text('/** Generated by tools/extract-terrain-visuals.py from Java trap/plant classes. */\n'
                  + 'export const TRAP_VISUALS: Record<string, number> = ' + json.dumps(traps, indent=2) + ';\n'
                  + 'export const PLANT_VISUALS: Record<string, number> = ' + json.dumps(plants, indent=2) + ';\n', encoding='utf-8')
print(f'Extracted {len(traps)} traps and {len(plants)} plants into {output}')
